# Language dictionary for multi-language support
LANG = {
    'fa': {
        'welcome': 'خوش آمدید به طلایار حرفه‌ای v4.1',
        'login_failed': 'نام کاربری یا رمز عبور اشتباه است',
        'dashboard': 'داشبورد',
        'customers': 'مشتریان',
        'invoices': 'فاکتورها',
        'settings': 'تنظیمات',
        'total_paid': 'کل پرداختی‌ها',
        'total_due': 'مبلغ باقی‌مانده',
        'avg_interest': 'میانگین کارمزد',
        'no_due_installments': 'هیچ قسطی نزدیک به سررسید نیست',
        'logout': 'خروج',
        'notifications': 'اعلانات',
        'reports': 'گزارش‌ها',
        'pay': 'پرداخت',
        'paid': 'پرداخت‌شده',
        'unpaid': 'پرداخت‌نشده',
        'products': 'کالاها',
        'installments': 'اقساط',
        'payment_type': 'نوع پرداخت',
        'cash': 'نقدی',
        'card_to_card': 'کارت به کارت',
        'sheba': 'شبا',
        'source_card': 'کارت مبدا',
        'destination_card': 'کارت مقصد',
        'source_sheba': 'شبا مبدا',
        'destination_sheba': 'شبا مقصد',
        'admin': 'ادمین',
        'invoice_number': 'شماره فاکتور',
        'total_installments': 'تعداد کل اقساط',
        'paid_installments': 'اقساط پرداخت‌شده',
        'unpaid_installments': 'اقساط پرداخت‌نشده',
        'total_debt': 'کل بدهی',
        'total_paid_amount': 'کل پرداختی',
        'remaining_balance': 'مانده',
        'create_installments': 'ایجاد اقساط',
        'start_date': 'تاریخ شروع',
        'installment_type': 'نوع قسط',
        'monthly': 'ماهانه',
        'weekly': 'هفتگی',
        'num_installments': 'تعداد اقساط',
        'interest_rate': 'نرخ کارمزد (%)',
        'amount_per_installment': 'مبلغ هر قسط',
        'create': 'ایجاد',
        'report_details': 'جزئیات گزارش',
        'created_at': 'تاریخ ثبت',
        'due_soon': 'نزدیک به سررسید',
        'profile': 'پروفایل',
        'name': 'نام',
        'family_name': 'نام خانوادگی',
        'phone': 'شماره تماس',
    },
    'en': {
        'welcome': 'Welcome to GoldManager Pro v4.1',
        'login_failed': 'Incorrect username or password',
        'dashboard': 'Dashboard',
        'customers': 'Customers',
        'invoices': 'Invoices',
        'settings': 'Settings',
        'total_paid': 'Total Paid',
        'total_due': 'Amount Due',
        'avg_interest': 'Average Interest',
        'no_due_installments': 'No installments due soon',
        'logout': 'Logout',
        'notifications': 'Notifications',
        'reports': 'Reports',
        'pay': 'Pay',
        'paid': 'Paid',
        'unpaid': 'Unpaid',
        'products': 'Products',
        'installments': 'Installments',
        'payment_type': 'Payment Type',
        'cash': 'Cash',
        'card_to_card': 'Card to Card',
        'sheba': 'Sheba',
        'source_card': 'Source Card',
        'destination_card': 'Destination Card',
        'source_sheba': 'Source Sheba',
        'destination_sheba': 'Destination Sheba',
        'admin': 'Admin',
        'invoice_number': 'Invoice Number',
        'total_installments': 'Total Installments',
        'paid_installments': 'Paid Installments',
        'unpaid_installments': 'Unpaid Installments',
        'total_debt': 'Total Debt',
        'total_paid_amount': 'Total Paid',
        'remaining_balance': 'Remaining Balance',
        'create_installments': 'Create Installments',
        'start_date': 'Start Date',
        'installment_type': 'Installment Type',
        'monthly': 'Monthly',
        'weekly': 'Weekly',
        'num_installments': 'Number of Installments',
        'interest_rate': 'Interest Rate (%)',
        'amount_per_installment': 'Amount per Installment',
        'create': 'Create',
        'report_details': 'Report Details',
        'created_at': 'Created At',
        'due_soon': 'Due Soon',
        'profile': 'Profile',
        'name': 'First Name',
        'family_name': 'Last Name',
        'phone': 'Phone Number',
    }
}

# Default language
CURRENT_LANG = 'fa'

def set_language(lang):
    """Set the current language."""
    global CURRENT_LANG
    if lang in ['fa', 'en']:
        CURRENT_LANG = lang
    else:
        raise ValueError("Invalid language code. Use 'fa' or 'en'.")

# UI Theme Settings
THEME = {
    'background': '#1C2526',
    'accent': '#D4AF37',
    'card_background': '#F5F5F5',
    'text_light': '#FFFFFF',
    'text_dark': '#333333',
    'button_fg': '#D4AF37',
    'button_hover': '#B8972F',
    'font_fa': ('IranSans', 14),
    'font_en': ('Roboto', 14),
    'font_bold': ('IranSans', 16, 'bold') if CURRENT_LANG == 'fa' else ('Roboto', 16, 'bold'),
    'font_small': ('IranSans', 12) if CURRENT_LANG == 'fa' else ('Roboto', 12),
}